apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "jet-factory-chart.fullname" . }}-server-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
