apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "jet-factory-chart.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-env
data:
  {{- .Values.env | toYaml | nindent 2}}
  DATABASE_URL: {{ include "jet-factory-chart.database-url" . }}

