{{- if .Values.slpTLSSecret | empty | not }}
{{- with .Values.slpTLSSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skylark-helm-chart.fullname" $ }}-tls-secret
  labels:
    {{ include "skylark-helm-chart.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Files.Get .certificate | b64enc }}
  tls.key: {{ $.Files.Get .key | b64enc }}
{{- end }}
{{- end }}
