apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "skylark-helm-chart.fullname" . }}-redirect-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
